apiVersion: app.stackit.cloud/v1
kind: DataLogger
metadata:
  labels:
    app.kubernetes.io/name: datalogger
    app.kubernetes.io/instance: datalogger-sample
    app.kubernetes.io/part-of: assessment-repo-content
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: assessment-repo-content
  name: datalogger-sample
  namespace: "my-namespace1"
  finalizers:
    - finalizer.stackit.cloud/datalogger
spec:
  replicas: 1
  custom-name: datalogger-sample
  port: 8080
  node-port: 32101
  target-port: 80
